routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\SanBong;
use App\KhachHangKhungGio;
use App\KhungGio;
use Carbon\Carbon;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//clear cache
Route::get('clearcache', function () {
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    return "Cache is cleared";
});

//nhan vien route
Route::group(['middleware' => ['auth']], function () {
    Route::resources([
        'staff' => StaffController::class,
    ]);

    Route::get('/', function () {
        return redirect(route('staff.index'));
    });

    Route::group(['prefix' => 'user'], function () {
        Route::get('danh-sach', 'UserController@index')->name('user.index');
        Route::get('them-moi', 'UserController@create')->name('user.create');
        Route::post('them-moi', 'UserController@store')->name('user.confirm.create');
        Route::get('cap-nhat/{id}', 'UserController@edit')->name('user.edit');
        Route::post('cap-nhat', 'UserController@update')->name('user.confirm.edit');
        Route::get('tim-kiem', 'UserController@search')->name('user.search');
        Route::delete('del_user/{id}', 'UserController@destroy')->name('del.user');
    });

    Route::resources([
        'san-bong' => 'SanBongController',
    ]);

    Route::resources([
        'khach-hang' => 'KhachHangController',
    ]);

    Route::resources([
        'khung-gio' => 'KhungGioController',
    ]);

    Route::resources([
        'khach-hang-khung-gio' => 'KhachHangKhungGioController',
    ]);

    Route::group(['prefix' => 'khach-hang-khung-gio'], function () {
//        Route::get('danh-sach', 'SanBongController@index')->name('sanbong.index');
//        Route::get('them-moi', 'SanBongController@create')->name('sanbong.create');
        Route::post('huy', 'KhachHangKhungGioController@cancel_all')->name('khach-hang-khung-gio.huy');
        Route::post('thanh-toan', 'KhachHangKhungGioController@confirm_payment')->name('khach-hang-khung-gio.post.payment');
        Route::get('thanh-toan/{id}', 'KhachHangKhungGioController@payment')->name('khach-hang-khung-gio.payment');
//        Route::get('cap-nhat/{id}', 'SanBongController@edit')->name('sanbong.edit');
//        Route::post('cap-nhat', 'SanBongController@update')->name('sanbong.confirm.edit');
//        Route::get('tim-kiem', 'SanBongController@search')->name('sanbong.search');
//        Route::delete('del_user/{id}', 'UserController@destroy')->name('del.sanbong');
    });

});

//Đăng nhập
Route::any('login', 'AuthController@login')->name('login');
//đăng xuất
Route::get('logout', 'AuthController@logout')->name('get.logout');

Route::get('migrate', function () {
    KhachHangKhungGio::query()->truncate();
    $period = \Carbon\CarbonPeriod::create('2020-10-10', '2020-12-31');
    $san_bongs = SanBong::all();
    $khunggios = KhungGio::all();
    $data_all = [];
    foreach ($period as $date) {
        foreach ($san_bongs as $san_bong) {
            foreach ($khunggios as $khunggio) {
                $data = [
                    'id_khung_gio' => $khunggio->id,
                    'id_san' => $san_bong->id,
                    'status' => 2,
                    'status_thanh_toan' => 2,
                    'active_date' => $date,
                    'created_at' => date('Y-m-d H:i'),
                    'updated_at' => date('Y-m-d H:i'),
                ];
                $data_all[] = $data;
            }
        }
    }

    KhachHangKhungGio::insert($data_all);
});

resources/views/component/layout/head.blade.php
<script src="{{asset('template/statics/html5shiv.js')}}"></script>
<script src="{{asset('template/statics/respond.min.js')}}"></script>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta name="csrf-token" content="{{ csrf_token() }}">
<!-- Favicon icon -->
{{----}}
<!-- Google font-->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet">
<!-- Required Fremwork -->
<link rel="stylesheet" type="text/css" href="{{asset('template/css/bootstrap.min.css')}}">
<!-- feather Awesome -->
<link rel="stylesheet" type="text/css" href="{{asset('template/css/feather.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('template/assets/pages/advance-elements/css/bootstrap-datetimepicker.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('template/assets/icon/ion-icon/css/ionicons.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('template/assets/icon/themify-icons/themify-icons.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('template/assets/icon/font-awesome/css/font-awesome.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('template/assets/pages/prism/prism.css')}}">
<link rel="stylesheet" href="{{asset('template/css/sweetalert.css')}}">
<!-- Style.css -->
<link rel="stylesheet" type="text/css" href="{{asset('template/css/style.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('template/css/jquery.mCustomScrollbar.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('css/custom.css')}}">
<script src="{{asset('template/js/sweetalert.min.js')}}"></script>

resources/views/component/layout/nav-header.blade.php
<nav class="navbar header-navbar pcoded-header">
    <div class="navbar-wrapper">

        <div class="navbar-logo">
            <a class="mobile-menu" id="mobile-collapse" href="#!">
                <i class="feather icon-menu"></i>
            </a>
            <a href="#">
                <h6>Quản lý sân bóng</h6>
            </a>
            <a class="mobile-options">
                <i class="feather icon-more-horizontal"></i>
            </a>
        </div>

        <div class="navbar-container container-fluid">
            <ul class="nav-right">
                <li class="user-profile header-notification">
                    <div class="dropdown-primary dropdown">
                        <div class="dropdown-toggle" data-toggle="dropdown">
                            @php
                                use Illuminate\Support\Facades\Auth;
                                $username = Auth::user() ? Auth::user()->name : 'Đoàn'
                            @endphp
                            <span>{{$username}}</span>
                            <i class="feather icon-chevron-down"></i>
                        </div>
                        <ul class="show-notification profile-notification dropdown-menu" data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">
                            <li>
                                <a href="{{route('get.logout')}}">
                                    <i class="feather icon-log-out"></i> Đăng xuất
                                </a>
                            </li>
                        </ul>

                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/component/layout/script.blade.php
<script type="text/javascript" src="{{asset('template/js/jquery.min.js')}}"></script>
<script type="text/javascript" src="{{asset('template/js/jquery-ui.min.js')}}"></script>
<script type="text/javascript" src="{{asset('template/js/popper.min.js')}}"></script>
<script type="text/javascript" src="{{asset('template/js/bootstrap.min.js')}}"></script>
<!--datepicker-->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script type="text/javascript" src="{{asset('template/js/bootstrap-datepicker.min.js')}}"></script>
<script type="text/javascript" src="{{asset('template/js/bootstrap-datetimepicker.min.js')}}"></script>
<script type="text/javascript" src="{{asset('template/js/datepicker.vi.js')}}"></script>
<!-- jquery slimscroll js -->
<script type="text/javascript" src="{{asset('template/js/jquery.slimscroll.js')}}"></script>

<script src="{{asset('template/js/jquery.mCustomScrollbar.concat.min.js')}}"></script>
<script type="text/javascript" src="{{asset('template/js/SmoothScroll.js')}}"></script>
<script src="{{asset('template/js/pcoded.min.js')}}"></script>
<!-- custom js -->
<script src="{{asset('template/js/vartical-layout.min.js')}}"></script>
<script type="text/javascript" src="{{asset('template/js/script.min.js')}}"></script>

resources/views/component/layout/sidebar.blade.php
<nav class="pcoded-navbar">
    <div class="pcoded-inner-navbar main-menu">
        <div class="pcoded-navigatio-lavel" menu-title-theme="theme5">Quản lý</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="">
                <a href="{{route('user.index')}}">
                    <span class="pcoded-micon"><i class="feather icon-user"></i></span>
                    <span class="pcoded-mtext">Quản lý tài khoản</span>
                </a>
            </li>
            <li class="">
                <a href="{{route('khach-hang.index')}}">
                    <span class="pcoded-micon"><i class="feather icon-users"></i></span>
                    <span class="pcoded-mtext">Quản lý khách hàng</span>
                </a>
            </li>
            <li class="">
                <a href="{{route('san-bong.index')}}">
                    <span class="pcoded-micon"><i class="fa fa-soccer-ball-o"></i></span>
                    <span class="pcoded-mtext">Quản lý sân bóng</span>
                </a>
            </li>
            <li class="">
                <a href="{{route('khung-gio.index')}}">
                    <span class="pcoded-micon"><i class="fa fa-calendar-o"></i></span>
                    <span class="pcoded-mtext">Quản lý khung giờ</span>
                </a>
            </li>
            <li class="">
                <a href="{{route('khach-hang-khung-gio.index')}}">
                    <span class="pcoded-micon"><i class="fa fa-gavel"></i></span>
                    <span class="pcoded-mtext">Quản lý yêu cầu đặt sân</span>
                </a>
            </li>
            {{--<li class="">--}}
                {{--<a href="navbar-light.htm">--}}
                    {{--<span class="pcoded-micon"><i class="feather icon-file-minus"></i></span>--}}
                    {{--<span class="pcoded-mtext">Quản lý hóa đơn</span>--}}
                {{--</a>--}}
            {{--</li>--}}
        </ul>
    </div>
</nav>

resources/views/component/layout/theme-loader.blade.php
<div class="theme-loader">
    <div class="ball-scale">
        <div class='contain'>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
        </div>
    </div>
</div>