routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\SanBong;
use App\KhachHangKhungGio;
use App\KhungGio;
use Carbon\Carbon;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//clear cache
Route::get('clearcache', function () {
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    return "Cache is cleared";
});

//nhan vien route
Route::group(['middleware' => ['auth']], function () {
    Route::resources([
        'staff' => StaffController::class,
    ]);

    Route::get('/', function () {
        return redirect(route('staff.index'));
    });

    Route::group(['prefix' => 'user'], function () {
        Route::get('danh-sach', 'UserController@index')->name('user.index');
        Route::get('them-moi', 'UserController@create')->name('user.create');
        Route::post('them-moi', 'UserController@store')->name('user.confirm.create');
        Route::get('cap-nhat/{id}', 'UserController@edit')->name('user.edit');
        Route::post('cap-nhat', 'UserController@update')->name('user.confirm.edit');
        Route::get('tim-kiem', 'UserController@search')->name('user.search');
        Route::delete('del_user/{id}', 'UserController@destroy')->name('del.user');
    });

    Route::resources([
        'san-bong' => 'SanBongController',
    ]);

    Route::resources([
        'khach-hang' => 'KhachHangController',
    ]);

    Route::resources([
        'khung-gio' => 'KhungGioController',
    ]);

    Route::resources([
        'khach-hang-khung-gio' => 'KhachHangKhungGioController',
    ]);

    Route::group(['prefix' => 'khach-hang-khung-gio'], function () {
//        Route::get('danh-sach', 'SanBongController@index')->name('sanbong.index');
//        Route::get('them-moi', 'SanBongController@create')->name('sanbong.create');
        Route::post('huy', 'KhachHangKhungGioController@cancel_all')->name('khach-hang-khung-gio.huy');
        Route::post('thanh-toan', 'KhachHangKhungGioController@confirm_payment')->name('khach-hang-khung-gio.post.payment');
        Route::get('thanh-toan/{id}', 'KhachHangKhungGioController@payment')->name('khach-hang-khung-gio.payment');
//        Route::get('cap-nhat/{id}', 'SanBongController@edit')->name('sanbong.edit');
//        Route::post('cap-nhat', 'SanBongController@update')->name('sanbong.confirm.edit');
//        Route::get('tim-kiem', 'SanBongController@search')->name('sanbong.search');
//        Route::delete('del_user/{id}', 'UserController@destroy')->name('del.sanbong');
    });

});

//Đăng nhập
Route::any('login', 'AuthController@login')->name('login');
//đăng xuất
Route::get('logout', 'AuthController@logout')->name('get.logout');

Route::get('migrate', function () {
    KhachHangKhungGio::query()->truncate();
    $period = \Carbon\CarbonPeriod::create('2020-10-10', '2020-12-31');
    $san_bongs = SanBong::all();
    $khunggios = KhungGio::all();
    $data_all = [];
    foreach ($period as $date) {
        foreach ($san_bongs as $san_bong) {
            foreach ($khunggios as $khunggio) {
                $data = [
                    'id_khung_gio' => $khunggio->id,
                    'id_san' => $san_bong->id,
                    'status' => 2,
                    'status_thanh_toan' => 2,
                    'active_date' => $date,
                    'created_at' => date('Y-m-d H:i'),
                    'updated_at' => date('Y-m-d H:i'),
                ];
                $data_all[] = $data;
            }
        }
    }

    KhachHangKhungGio::insert($data_all);
});

app/KhachHangKhungGio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class KhachHangKhungGio extends Model
{
//    use SoftDeletess;
    protected $fillable = [
        'id_khach_hang','id_khung_gio','active_date','id_san','status','id_user','updated_at',
        'thanh_toan','status_thanh_toan','deleted_at','type'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */

    protected $table = 'khachhang_khunggio';
    protected $perPage = 15;

    public function customer()
    {
        return $this->belongsTo('App\KhachHang', 'id_khach_hang', 'id');
    }

    public function san()
    {
        return $this->belongsTo('App\SanBong', 'id_san', 'id');
    }

    public function khunggio()
    {
        return $this->belongsTo('App\KhungGio', 'id_khung_gio', 'id');
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'id_user', 'id');
    }
}

app/Http/Controllers/KhachHangKhungGioController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\KhachHangKhungGioRequest;
use App\KhachHang;
use App\KhachHangKhungGio;
use App\KhungGio;
use App\SanBong;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class KhachHangKhungGioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $time = KhungGio::get();
        $customer = KhachHang::get();
        $calendar = KhachHangKhungGio::with('customer', 'san', 'user', 'khunggio')->where(function ($q) use ($request) {
            if ($request->search) {
                $q->where('name', 'like', '%' . $request->search . '%')
                    ->orWhere('code', 'like', '%' . $request->search . '%');
            }
            if ($request->timeframe) {
                $q->where('id_khung_gio', $request->timeframe);
            }
            if ($request->timeframe) {
                $q->where('id_khach_hang', $request->customer);
            }
            if ($request->active_date) {
                $q->where('active_date', $request->active_date);
            }
            if ($request->status) {
                $q->where('status', $request->status);
            }
        })->paginate($request->raw);
        return view('component.khachhang-khunggio.index', compact('calendar', 'time', 'customer'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $time = KhungGio::get();
        $customer = KhachHang::get();
        return view('component.dat-san.index', compact('time', 'customer'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\KhachHangKhungGio $khachHangKhungGio
     * @return \Illuminate\Http\Response
     */
    public function show(KhachHangKhungGio $khachHangKhungGio)
    {
        $time = KhungGio::get();
        $customer = KhachHang::get();
        $san = SanBong::get();
        return view('component.khachhang-khunggio.view', compact('time', 'customer', 'khachHangKhungGio', 'san'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\KhachHangKhungGio $khachHangKhungGio
     * @return \Illuminate\Http\Response
     */
    public function edit(KhachHangKhungGio $khachHangKhungGio)
    {
        $time = KhungGio::get();
        $customer = KhachHang::get();
        $san = SanBong::get();
        return view('component.dat-san.index', compact('time', 'customer', 'khachHangKhungGio', 'san'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\KhachHangKhungGio $khachHangKhungGio
     * @return \Illuminate\Http\Response
     */
    public function update(KhachHangKhungGioRequest $request, KhachHangKhungGio $khachHangKhungGio)
    {
        try {
            $code = generate_code_customer();
            $customer = KhachHang::updateOrCreate(
                [
                    'phone' => request('phone')
                ],
                [
                    'code' => $code,
                    'name' => $request->name,
                    'created_by' => Auth::user()->id,
                    'email' => $request->email,
                    'address' => $request->address,
                    'gender' => $request->gender,
                ]
            );
            if (request('type') == 1) {
                KhachHangKhungGio::where('id_khung_gio', $khachHangKhungGio->id_khung_gio)
                    ->where('id_san', $khachHangKhungGio->id_san)
                    ->whereBetween('active_date', [Carbon::today(), '2020-12-31'])->update([
                        'id_khach_hang' => $customer->id,
                        'status' => 1,
                        'type' => request('type')
                    ]);

            } else {
                $khachHangKhungGio->update(
                    [
                        'id_khach_hang' => $customer->id,
                        'status' => 1,
                        'type' => request('type')
                    ]
                );
            }
            return redirect()->route('khach-hang-khung-gio.index')->with(['status' => 'success', 'message' => 'Đặt sân thành công']);

        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
            return back()->with(['status' => 'error', 'message' => 'Đặt sân không thành công']);
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\KhachHangKhungGio $khachHangKhungGio
     * @return \Illuminate\Http\Response
     */
    public function destroy(KhachHangKhungGio $khachHangKhungGio)
    {
        try {
            $khachHangKhungGio->update([
                'status' => 2
            ]);
            return response()->json([
                'status' => 'success',
                'message' => 'Xóa hủy đặt sân thành công'
            ], 200);
        } catch (\Exception $ex) {
            return response()->json([
                'status' => 'error',
                'message' => 'Có lỗi xảy ra'
            ], 500);
        }
    }

    public function cancel_all(Request $request)
    {
        try {
            $khachHangKhungGio = KhachHangKhungGio::findOrFail($request->id);
            $data = KhachHangKhungGio::where('id_khung_gio', $khachHangKhungGio->id_khung_gio)
                ->where('id_san', $khachHangKhungGio->id_san)
                ->whereBetween('active_date', [Carbon::today(), '2020-12-31'])
                ->update([
                    'id_khach_hang' => null,
                    'status' => 2,
                    'status_thanh_toan' => 2,
                    'type' => null
                ]);
//            dd($data,$khachHangKhungGio);
            return redirect()->route('khach-hang-khung-gio.index')->with(['status' => 'success', 'message' => 'Hủy hợp đồng thành công']);
        } catch (\Exception $ex) {
            return response()->json([
                'status' => 'error',
                'message' => 'Có lỗi xảy ra'
            ], 500);
        }
    }

    public function payment($id) {
        $khachHangKhungGio = KhachHangKhungGio::findOrFail($id);
//        dd($khachHangKhungGio);
        $time = KhungGio::get();
        $customer = KhachHang::get();
        $san = SanBong::get();
        return view('component.dat-san.payment', compact('time','customer','san','khachHangKhungGio'));
    }

    public function confirm_payment(Request $request) {

        if($request->price >= $request->payment) {
            $payment = 1;
        } else {
            $payment = 2;
        }
        KhachHangKhungGio::find($request->id)->update([
            'status_thanh_toan'=>$payment,
        ]);
        return redirect()->route('khach-hang-khung-gio.index')->with(['status' => 'success', 'message' => 'Thanh toán thành công']);
    }
}

resources/views/component/khachhang-khunggio/_search.blade.php
<div>
    <form id="form-search" method="get" action="{{route('khach-hang-khung-gio.index')}}">

        <div class="form-row">
            <div class="col-md-3">
                <label class="col-form-label">Trạng thái sân</label>
                <select style="height: 34px" class="form-control form-control-sm js-select2-no-search"
                        name="status">
                    <option value="">--- Trạng thái sân ---</option>
                    <option @if(request('status') == 1) selected
                            @endif value="1">Đã đặt
                    </option>
                    <option @if(request('status') == 2) selected
                            @endif value="2">Chưa đặt
                    </option>
                </select>
            </div>
            <div class="col-md-3">
                <label class="col-form-label">Tên khách hàng</label>
                <select style="height: 34px" class="form-control form-control-sm js-select2-no-search"
                        name="customer">
                    <option value="">--- Tên khách hàng ---</option>
                    @foreach($customer as $key => $value)
                        <option @if(request('customer') == $key+1) selected
                                @endif value="{{$value->id}}">{{$value['name']}}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-md-3">
                <label class="col-form-label">Ngày đá</label>
                <input style="height: 34px" id="search_input" type="date" class="form-control"
                       name="active_date" value="{{request('active_date')}}">
            </div>

            <div class="col-md-3">
                <label class="col-form-label">Khung giờ</label>
                <select style="height: 34px" class="form-control form-control-sm js-select2-no-search"
                        id="search_service"
                        name="timeframe">
                    <option value="">--- Khung giờ ---</option>
                    @foreach($time as $key => $value)
                        <option @if(request('timeframe') == $key+1) selected
                                @endif value="{{$value->id}}">{{$value['name']}}</option>
                    @endforeach
                </select>
            </div>

        </div>
        <br/>
        <div class="row">
            <div class="form-group col-md-1">
                <button class="btn btn-inverse btn-sm" type="submit" title="Tìm kiếm">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </form>
</div>

resources/views/component/khachhang-khunggio/create.blade.php
@extends('app')
@section('head.title')
    Đặt sân
@endsection
@section('content')
    <div class="page-header m-t-150 page-header-index">
        <div class="row">
            <div class="col-lg-12 p-t-5">
                <div class="page-header-title p-l-10">
                    <div class="d-inline">
                        <h4>Thêm mới khung giờ</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="card card-index">
            <div class="card-block">
                <form class="forms-sample" method="post" action="{{route('khung-gio.store')}}">
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="form-group col-md-3">
                            <label class="col-form-label">Mã khung giờ<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" name="code" value="{{ old('code') }}"
                                   autocomplete="off" maxlength="50">
                            @if ($errors->has('code'))
                                <p class="text-danger">{{$errors->first('code')}}</p>
                            @endif
                        </div>
                        <div class="form-group col-md-3">
                            <label class="col-form-label">Tên khung giờ<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" name="name" value="{{ old('name') }}"
                                   autocomplete="off" maxlength="255">
                            @if ($errors->has('name'))
                                <p class="text-danger">{{$errors->first('name')}}</p>
                            @endif
                        </div>
                        <div class="form-group col-md-3">
                            <label class="col-form-label">Thời gian bắt đầu <span class="text-danger">*</span></label>
                            <input type="time" class="form-control" name="start_time"  value="{{ old('start_time')}}">
                            @if ($errors->has('start_time'))
                                <p class="text-danger">{{$errors->first('start_time')}}</p>
                            @endif
                        </div>
                        <div class="form-group col-md-3">
                            <label class="col-form-label">Thời gian kết thúc <span class="text-danger">*</span></label>
                            <input type="time" class="form-control" name="end_time" value="{{ old('end_time') }}"
                                   autocomplete="off" maxlength="50">
                            @if ($errors->has('end_time'))
                                <p class="text-danger">{{$errors->first('end_time')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-3">
                            <label class="col-form-label">Giá tiền<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" name="price" value="{{ old('price') }}"
                                   autocomplete="off" maxlength="50">
                            @if ($errors->has('price'))
                                <p class="text-danger">{{$errors->first('price')}}</p>
                            @endif
                        </div>
                    </div>

                    <hr>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary mr-2 add btn-sm a-font-size-13" title="Lưu mới">
                            <i class="fa fa-save"></i> Lưu mới
                        </button>
                        <a href="{{route('khung-gio.index')}}" class="btn btn-secondary btn-sm a-font-size-13"
                           title="Quay lại">
                            <i class="fa fa-arrow-left"></i> Quay lại
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script type="module" src="{{asset('js/modules/khung-gio.js')}}"></script>
@endsection

resources/views/component/khachhang-khunggio/index.blade.php
@extends('app')
@section('head.title')
    Quản lý đặt sân
@endsection
@section('content')
    <div class="page-header m-t-150 page-header-index">
        <div class="row">
            <div class="col-lg-8 p-t-5">
                <div class="page-header-title p-l-10">
                    <div class="d-inline">
                        <h4>Quản lý đặt sân</h4>
                    </div>
                </div>
            </div>
            {{--<div class="col-lg-4">--}}
                {{--<div class="float-right p-r-10">--}}
                    {{--<a class="btn btn-primary btn-sm color-white" title="Thêm mới"--}}
                       {{--href="{{route('khach-hang-khung-gio.create')}}">--}}
                        {{--<i class="fa fa-plus"></i> Thêm mới--}}
                    {{--</a>--}}
                {{--</div>--}}
            {{--</div>--}}
        </div>
    </div>
    <div class="page-body">
        <div class="card card-index">
            <div class="card-header p-b-15 p-t-10 header-form-search">
                @include('component.khachhang-khunggio._search',$customer)

            </div>
            <div class="card-body p-t-0">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-custom">
                        <thead class="t-head-inverse">
                        <tr>
                            <th>STT</th>
                            <th>Tên sân</th>
                            <th>Tên khung giờ</th>
                            <th>Tên khách hàng</th>
                            <th>Ngày</th>
                            <th>Trạng thái</th>
                            <th>TT thanh toán</th>
                            <th>Thanh toán</th>
                            <th>Tác vụ</th>
                        </tr>
                        </thead>
                        <tbody>

                        @php
                            $index = $calendar->perpage() * ($calendar->currentPage() - 1);
                        @endphp
                        @foreach($calendar as $key => $value)
                            <tr>
                                <td class="text-center">{{$key + 1 + $index}}</td>
                                <td>{{$value->san->name ?? ''}}</td>
                                <td>{{$value->khunggio->name ?? ''}}</td>
                                <td>{{$value->customer->name ?? ''}}</td>
                                <td>{{$value->active_date}}</td>
                                <td class="text-center">
                                    @if ($value->status == 1)
                                        <label class="badge badge-success">Đã đặt</label>
                                    @else
                                        <label class="badge badge-danger">Chưa đặt</label>
                                    @endif
                                </td>

                                <td class="text-center">
                                    @if ($value->status_thanh_toan == 1)
                                        <label class="badge badge-info">Đã thanh toán</label>
                                    @else
                                        <label class="badge badge-warning">Chưa thanh toán</label>
                                    @endif
                                <td>{{$value->thanh_toan ? $value->thanh_toan:'0'}}</td>
                                <td class="text-center">
                                    <a class="p-l-5" href="{{route('khach-hang-khung-gio.edit', $value->id)}}"
                                       title="Đặt sân">
                                        <i class="fa fa-calendar-check-o fa-lg"></i>
                                    </a>
                                    <a class="color-red p-l-5"
                                       href="{{route('khach-hang-khung-gio.payment', $value->id)}}" title="Thanh toán">
                                        <i class="fa fa-money fa-lg" ></i>
                                    </a>
                                    <a class=" color-red p-l-5"
                                       href="{{route('khach-hang-khung-gio.show', $value->id)}}" title="Xem chi tiết">
                                        <i class="fa fa-info-circle fa-lg" ></i>
                                    </a>
                                    {{--<i class="fa fa-money"></i>--}}
                                    <a class="cancel color-red p-l-5" data-id="{{$value->id}}" style="color: red"
                                       href="javascript:void(0)" title="Hủy đặt sân">
                                        <i class="fa fa-times-circle-o fa-lg" ></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                        <tfoot>
                        @include('component.pagination', ['column' => 9, 'datas' => $calendar])
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
        @include('component.flash-message')
    </div>
@endsection
@section('script')
    <script type="module" src="{{asset('js/modules/datsan.js')}}"></script>
@endsection

resources/views/component/khachhang-khunggio/update.blade.php
@extends('app')
@section('head.title')
    Chỉnh sửa lịch đặt sân
@endsection
@section('content')
    <div class="page-header m-t-150 page-header-index">
        <div class="row">
            <div class="col-lg-12 p-t-5">
                <div class="page-header-title p-l-10">
                    <div class="d-inline">
                        <h4>Chỉnh sửa lịch đặt sân</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="card card-index">
            <div class="card-block">
                <form class="forms-sample" method="POST" action="{{route('khung-gio.update', $timeframe->id)}}">
                    @csrf
                    @method('PATCH')
                    <div class="row">
                        <div class="form-group col-md-3">
                            <input type="text" class="form-control" name="id" value={{ $timeframe->id }} hidden>
                            <label class="col-form-label">Mã khung giờ<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" name="code" value="{{ $timeframe->code }}"
                                   autocomplete="off" maxlength="50" readonly>
                            @if ($errors->has('code'))
                                <p class="text-danger">{{$errors->first('code')}}</p>
                            @endif
                        </div>
                        <div class="form-group col-md-3">
                            <label class="col-form-label">Tên khung giờ<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" name="name" value="{{ $timeframe->name }}"
                                   autocomplete="off" maxlength="255">
                            @if ($errors->has('name'))
                                <p class="text-danger">{{$errors->first('name')}}</p>
                            @endif
                        </div>
                        <div class="form-group col-md-3">
                            <label class="col-form-label">Thời gian bắt đầu <span class="text-danger">*</span></label>
                            <input type="time" class="form-control" name="start_time" value="{{ $timeframe->start_time}}">
                            @if ($errors->has('start_time'))
                                <p class="text-danger">{{$errors->first('start_time')}}</p>
                            @endif
                        </div>
                        <div class="form-group col-md-3">
                            <label class="col-form-label">Thời gian kết thúc <span class="text-danger">*</span></label>
                            <input type="time" class="form-control" name="end_time" value="{{ $timeframe->end_time }}"
                                   autocomplete="off" maxlength="50">
                            @if ($errors->has('end_time'))
                                <p class="text-danger">{{$errors->first('end_time')}}</p>
                            @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-3">
                            <label class="col-form-label">Giá tiền<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" name="price" value="{{ $timeframe->price }}"
                                   autocomplete="off" maxlength="50">
                            @if ($errors->has('price'))
                                <p class="text-danger">{{$errors->first('price')}}</p>
                            @endif
                        </div>
                    </div>

                    <hr>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary mr-2 add btn-sm a-font-size-13" title="Cập nhật">
                            <i class="fa fa-save"></i> Cập nhật
                        </button>
                        <a href="{{route('khung-gio.index')}}" class="btn btn-secondary btn-sm a-font-size-13"
                           title="Quay lại">
                            <i class="fa fa-arrow-left"></i> Quay lại
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script type="module" src="{{asset('js/modules/khunggio.js')}}"></script>
@endsection