routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\SanBong;
use App\KhachHangKhungGio;
use App\KhungGio;
use Carbon\Carbon;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//clear cache
Route::get('clearcache', function () {
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    return "Cache is cleared";
});

//nhan vien route
Route::group(['middleware' => ['auth']], function () {
    Route::resources([
        'staff' => StaffController::class,
    ]);

    Route::get('/', function () {
        return redirect(route('staff.index'));
    });

    Route::group(['prefix' => 'user'], function () {
        Route::get('danh-sach', 'UserController@index')->name('user.index');
        Route::get('them-moi', 'UserController@create')->name('user.create');
        Route::post('them-moi', 'UserController@store')->name('user.confirm.create');
        Route::get('cap-nhat/{id}', 'UserController@edit')->name('user.edit');
        Route::post('cap-nhat', 'UserController@update')->name('user.confirm.edit');
        Route::get('tim-kiem', 'UserController@search')->name('user.search');
        Route::delete('del_user/{id}', 'UserController@destroy')->name('del.user');
    });

    Route::resources([
        'san-bong' => 'SanBongController',
    ]);

    Route::resources([
        'khach-hang' => 'KhachHangController',
    ]);

    Route::resources([
        'khung-gio' => 'KhungGioController',
    ]);

    Route::resources([
        'khach-hang-khung-gio' => 'KhachHangKhungGioController',
    ]);

    Route::group(['prefix' => 'khach-hang-khung-gio'], function () {
//        Route::get('danh-sach', 'SanBongController@index')->name('sanbong.index');
//        Route::get('them-moi', 'SanBongController@create')->name('sanbong.create');
        Route::post('huy', 'KhachHangKhungGioController@cancel_all')->name('khach-hang-khung-gio.huy');
        Route::post('thanh-toan', 'KhachHangKhungGioController@confirm_payment')->name('khach-hang-khung-gio.post.payment');
        Route::get('thanh-toan/{id}', 'KhachHangKhungGioController@payment')->name('khach-hang-khung-gio.payment');
//        Route::get('cap-nhat/{id}', 'SanBongController@edit')->name('sanbong.edit');
//        Route::post('cap-nhat', 'SanBongController@update')->name('sanbong.confirm.edit');
//        Route::get('tim-kiem', 'SanBongController@search')->name('sanbong.search');
//        Route::delete('del_user/{id}', 'UserController@destroy')->name('del.sanbong');
    });

});

//Đăng nhập
Route::any('login', 'AuthController@login')->name('login');
//đăng xuất
Route::get('logout', 'AuthController@logout')->name('get.logout');

Route::get('migrate', function () {
    KhachHangKhungGio::query()->truncate();
    $period = \Carbon\CarbonPeriod::create('2020-10-10', '2020-12-31');
    $san_bongs = SanBong::all();
    $khunggios = KhungGio::all();
    $data_all = [];
    foreach ($period as $date) {
        foreach ($san_bongs as $san_bong) {
            foreach ($khunggios as $khunggio) {
                $data = [
                    'id_khung_gio' => $khunggio->id,
                    'id_san' => $san_bong->id,
                    'status' => 2,
                    'status_thanh_toan' => 2,
                    'active_date' => $date,
                    'created_at' => date('Y-m-d H:i'),
                    'updated_at' => date('Y-m-d H:i'),
                ];
                $data_all[] = $data;
            }
        }
    }

    KhachHangKhungGio::insert($data_all);
});

app/SanBong.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class SanBong extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','code',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $table = 'san_bong';
    protected $perPage = 15;
}

app/Http/Controllers/SanBongController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SanBongRequest;
use App\SanBong;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class SanBongController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $pitch = SanBong::where(function ($q) use ($request) {
            if ($request->search) {
                $q->where('name', 'like', '%' . $request->search . '%')
                    ->orWhere('code', 'like', '%' . $request->search . '%');
            }
        })->paginate($request->raw);
        return view('component.sanbong.index', compact('pitch'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('component.sanbong.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(SanBongRequest $request)
    {
        try {
            SanBong::create([
                'code' => $request->code,
                'name' => $request->name,
            ]);
            return redirect()->route('san-bong.index')->with(['status' => 'success', 'message' => 'Thêm mới thành công']);
        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
            return back()->with(['status' => 'error', 'message' => 'Thêm mới sân bóng không thành công']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\SanBong $sanBong
     * @return \Illuminate\Http\Response
     */
    public function show(SanBong $sanBong)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\SanBong $sanBong
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pitch = SanBong::findOrFail($id);
        return view('component.sanbong.update', compact('pitch'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\SanBong $sanBong
     * @return \Illuminate\Http\Response
     */
    public function update(SanBongRequest $request)
    {
        try {
            $data = [
                'name' => $request->name,
            ];

            SanBong::find($request->id)->update($data);
            return redirect()->route('san-bong.index')->with(['status' => 'success', 'message' => 'Chỉnh sửa thành công']);
        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
            return back()->with(['status' => 'error', 'message' => 'Chỉnh sửa tài khoản không thành công']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\SanBong $sanBong
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            SanBong::destroy($id);
            return response()->json([
                'status' => 'success',
                'message' => 'Xóa bản ghi thành công'
            ], 200);
        } catch (\Exception $ex) {
            return response()->json([
                'status' => 'error',
                'message' => 'Có lỗi xảy ra'
            ], 500);
        }
    }
}

resources/views/component/sanbong/_search.blade.php
<div>
    <form id="form-search" method="get" action="{{route('san-bong.index')}}">
        <div class="form-row">
            <div class="col-md-3">
                <input id="search_input" type="text" class="form-control" name="search" placeholder="Mã hoặc tên sân" value="{{request('search')}}">
            </div>
            <div class="col-md-1">
                <button class="btn btn-inverse btn-sm" type="submit" title="Tìm kiếm">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </form>
</div>

resources/views/component/sanbong/create.blade.php
@extends('app')
@section('head.title')
    Thêm mới sân bóng
@endsection
@section('content')
    <div class="page-header m-t-150 page-header-index">
        <div class="row">
            <div class="col-lg-12 p-t-5">
                <div class="page-header-title p-l-10">
                    <div class="d-inline">
                        <h4>Thêm mới sân bóng</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="card card-index">
            <div class="card-block">
                <form class="forms-sample" method="post" action="{{route('san-bong.store')}}">
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="form-group col-md-3">
                            <label class="col-form-label">Mã sân bóng<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" name="code" value="{{ old('code') }}" autocomplete="off" maxlength="50">
                            @if ($errors->has('code'))
                                <p class="text-danger">{{$errors->first('code')}}</p>
                            @endif
                        </div>
                        <div class="form-group col-md-3">
                            <label class="col-form-label">Tên sân bóng<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" name="name" value="{{ old('name') }}" autocomplete="off" maxlength="255">
                            @if ($errors->has('name'))
                                <p class="text-danger">{{$errors->first('name')}}</p>
                            @endif
                        </div>
                        {{--<div class="form-group col-md-3">--}}
                            {{--<label class="col-form-label">Số điện thoại</label>--}}
                            {{--<input type="text" class="form-control" name="phone" maxlength="20">--}}
                            {{--@if ($errors->has('phone'))--}}
                                {{--<p class="text-danger">{{$errors->first('phone')}}</p>--}}
                            {{--@endif--}}
                        {{--</div>--}}
                        {{--<div class="form-group col-md-3">--}}
                            {{--<label class="col-form-label">Email</label>--}}
                            {{--<input type="text" class="form-control" name="email" value="{{ old('email') }}"--}}
                                   {{--autocomplete="off" maxlength="50">--}}
                            {{--@if ($errors->has('email'))--}}
                                {{--<p class="text-danger">{{$errors->first('email')}}</p>--}}
                            {{--@endif--}}
                        {{--</div>--}}
                    </div>

                    <hr>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary mr-2 add btn-sm a-font-size-13" title="Lưu mới">
                            <i class="fa fa-save"></i> Lưu mới
                        </button>
                        <a href="{{route('san-bong.index')}}" class="btn btn-secondary btn-sm a-font-size-13"
                           title="Quay lại">
                            <i class="fa fa-arrow-left"></i> Quay lại
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script type="module" src="{{asset('js/modules/san-bong.js')}}"></script>
@endsection

resources/views/component/sanbong/index.blade.php
@extends('app')
@section('head.title')
    Quản lý sân bóng
@endsection
@section('content')
    <div class="page-header m-t-150 page-header-index">
        <div class="row">
            <div class="col-lg-8 p-t-5">
                <div class="page-header-title p-l-10">
                    <div class="d-inline">
                        <h4>Quản lý sân bóng</h4>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="float-right p-r-10">
                    <a class="btn btn-primary btn-sm color-white" title="Thêm mới" href="{{route('san-bong.create')}}">
                        <i class="fa fa-plus"></i> Thêm mới
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="card card-index">
            <div class="card-header p-b-15 p-t-10 header-form-search">
                @include('component.sanbong._search')
            </div>
            <div class="card-body p-t-0">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-custom">
                        <thead class="t-head-inverse">
                        <tr>
                            <th>STT</th>
                            <th>Mã</th>
                            <th>Tên Sân</th>
                            <th>Tác vụ</th>
                        </tr>
                        </thead>
                        <tbody>
                        @php
                            $index = $pitch->perpage() * ($pitch->currentPage() - 1);
                        @endphp
                        @foreach($pitch as $key => $value)
                            <tr>
                                <td class="text-center">{{$key + 1 + $index}}</td>
                                <td>{{$value->code}}</td>
                                <td>{{$value->name}}</td>
                                <td class="text-center">
                                    <a class="p-l-5" href="{{route('san-bong.edit', $value->id)}}" title="Chỉnh sửa">
                                        <i class="fa fa-edit fa-lg"></i>
                                    </a>

                                    <a class="del-record color-red p-l-5" data-id="{{$value->id}}"
                                       href="javascript:void(0)">
                                        <i class="fa fa-trash fa-lg" title="Xóa"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                        <tfoot>
                        @include('component.pagination', ['column' => 7, 'datas' => $pitch])
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
        @include('component.flash-message')
    </div>
@endsection
@section('script')
    <script type="module" src="{{asset('js/modules/sanbong.js')}}"></script>
@endsection

resources/views/component/sanbong/update.blade.php
@extends('app')
@section('head.title')
    Chỉnh sửa sân bóng
@endsection
@section('content')
    <div class="page-header m-t-150 page-header-index">
        <div class="row">
            <div class="col-lg-12 p-t-5">
                <div class="page-header-title p-l-10">
                    <div class="d-inline">
                        <h4>Chỉnh sửa sân bóng</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="card card-index">
            <div class="card-block">
                <form class="forms-sample" method="POST" action="{{route('san-bong.update', $pitch->id)}}">
                    @csrf
                    @method('PATCH')
                    <div class="row">
                        <div class="form-group col-md-3">
                            <input type="text" class="form-control" name="id" value="{{ $pitch->id }}" hidden>
                            <label class="col-form-label">Mã sân bóng<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" name="code" value="{{ $pitch->code }}" autocomplete="off" maxlength="50" readonly>
                            @if ($errors->has('code'))
                                <p class="text-danger">{{$errors->first('code')}}</p>
                            @endif
                        </div>
                        <div class="form-group col-md-3">
                            <label class="col-form-label">Tên sân bóng<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" name="name" value="{{ $pitch->name }}" autocomplete="off" maxlength="255">
                            @if ($errors->has('name'))
                                <p class="text-danger">{{$errors->first('name')}}</p>
                            @endif
                        </div>
                        {{--<div class="form-group col-md-3">--}}
                            {{--<label class="col-form-label">Số điện thoại</label>--}}
                            {{--<input type="text" class="form-control" name="phone" value="{{$user->phone}}" maxlength="20">--}}
                            {{--@if ($errors->has('phone'))--}}
                                {{--<p class="text-danger">{{$errors->first('phone')}}</p>--}}
                            {{--@endif--}}
                        {{--</div>--}}
                        {{--<div class="form-group col-md-3">--}}
                            {{--<label class="col-form-label">Email</label>--}}
                            {{--<input type="text" class="form-control" name="email" value="{{ $user->email }}"--}}
                                   {{--autocomplete="off" maxlength="50">--}}
                            {{--@if ($errors->has('email'))--}}
                                {{--<p class="text-danger">{{$errors->first('email')}}</p>--}}
                            {{--@endif--}}
                        {{--</div>--}}
                    </div>

                    <hr>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary mr-2 add btn-sm a-font-size-13" title="Cập nhật">
                            <i class="fa fa-save"></i> Cập nhật
                        </button>
                        <a href="{{route('san-bong.index')}}" class="btn btn-secondary btn-sm a-font-size-13"
                           title="Quay lại">
                            <i class="fa fa-arrow-left"></i> Quay lại
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script type="module" src="{{asset('js/modules/sanbong.js')}}"></script>
@endsection